import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';

const prisma = new PrismaClient();

const SEED_EMAILS = [
  'aria@sociall.com',
  'kabir@sociall.com',
  'zara@sociall.com',
  'rohan@sociall.com',
  'elena@sociall.com',
  'vikram@sociall.com',
  'maya@sociall.com',
  'arjun@sociall.com',
  'meera@sociall.com',
  'dev@sociall.com'
];

async function dryRun() {
  const users = await prisma.user.findMany({
    where: {
      OR: [
        { email: { endsWith: '@sociall.com' } },
        { email: { endsWith: '@example.com' } },
        { email: { contains: 'test' } },
        { email: { contains: 'e2e' } }
      ]
    },
    include: {
      profile: true,
      _count: {
        select: {
          posts: true,
          stories: true,
          comments: true,
          likes: true,
          followers: true,
          following: true,
          messagesSent: true,
          notifications: true,
        }
      }
    }
  });

  const report = {
    A: [] as any[],
    B: [] as any[],
    C: [] as any[]
  };

  users.forEach(u => {
    const email = u.email || '';
    let classification = 'C';
    let isSeed = false;
    let isE2E = false;

    if (SEED_EMAILS.includes(email)) {
      classification = 'A';
      isSeed = true;
    } else if (email.match(/^(e2e|test).*@example\.com$/)) {
      classification = 'B';
      isE2E = true;
    } else {
      classification = 'C';
    }

    const item = {
      email,
      username: u.profile?.username || '',
      userId: u.id,
      createdAt: u.createdAt,
      isSeed,
      isE2E,
      interactionsCount: u._count.posts + u._count.stories + u._count.comments + u._count.likes + u._count.followers + u._count.following + u._count.messagesSent + u._count.notifications,
      posts: u._count.posts,
      stories: u._count.stories,
      messages: u._count.messagesSent
    };

    report[classification as keyof typeof report].push(item);
  });

  let md = `# Dry Run: Test Account Classification\n\n`;

  md += `## A. CONFIRMED SEED ACCOUNTS (Safe to Delete)\n`;
  md += `These are the 10 explicitly defined accounts generated by \`npm run seed\`.\n\n`;
  md += `| Email | Username | ID | Posts | Stories | Messages | Total Interactions |\n`;
  md += `|---|---|---|---|---|---|---|\n`;
  report.A.forEach(u => {
    md += `| ${u.email} | ${u.username} | ${u.userId} | ${u.posts} | ${u.stories} | ${u.messages} | ${u.interactionsCount} |\n`;
  });
  md += `\n**Total Seed Accounts:** ${report.A.length}\n\n`;

  md += `## B. CONFIRMED E2E ACCOUNTS (Safe to Delete)\n`;
  md += `These accounts match the known dynamic Playwright patterns (e.g. \`e2e_*@example.com\`, \`test-*@example.com\`).\n\n`;
  md += `<details><summary>Click to view ${report.B.length} E2E accounts</summary>\n\n`;
  md += `| Email | Username | ID | Posts | Stories | Messages | Total Interactions |\n`;
  md += `|---|---|---|---|---|---|---|\n`;
  report.B.forEach(u => {
    md += `| ${u.email} | ${u.username} | ${u.userId} | ${u.posts} | ${u.stories} | ${u.messages} | ${u.interactionsCount} |\n`;
  });
  md += `\n</details>\n\n`;

  md += `## C. UNKNOWN / POSSIBLY REAL (DO NOT DELETE)\n`;
  md += `These accounts end with \`@sociall.com\` or \`@example.com\` or contain "test"/"e2e" but DO NOT perfectly match the known test patterns.\n\n`;
  if (report.C.length === 0) {
    md += `*No accounts fell into this category.* All accounts flagged were successfully classified as A or B.\n\n`;
  } else {
    md += `| Email | Username | ID | Posts | Stories | Messages | Total Interactions |\n`;
    md += `|---|---|---|---|---|---|---|\n`;
    report.C.forEach(u => {
      md += `| ${u.email} | ${u.username} | ${u.userId} | ${u.posts} | ${u.stories} | ${u.messages} | ${u.interactionsCount} |\n`;
    });
    md += `\n**Total Unknown Accounts:** ${report.C.length}\n\n`;
  }

  md += `## Next Steps\n`;
  md += `If you approve this classification, I will proceed to **delete all accounts in category A and B only**. No accounts in category C (if any exist) or outside of this list will be touched.\n`;

  fs.writeFileSync('C:/Users/HP/.gemini/antigravity-ide/brain/d6554750-d751-45d1-b57c-832a2cd7c4ae/implementation_plan.md', md);
  console.log('Artifact updated!');
}

dryRun().catch(console.error).finally(() => prisma.$disconnect());
