const fs = require('fs');

const data = JSON.parse(fs.readFileSync('test_users_report.json', 'utf8'));

let md = `# Dry Run: Test Account Classification\n\n`;

md += `## A. CONFIRMED SEED ACCOUNTS (Safe to Delete)\n`;
md += `These are the 10 explicitly defined accounts generated by \`npm run seed\`.\n\n`;
md += `| Email | Username | ID | Posts | Stories | Messages | Total Interactions |\n`;
md += `|---|---|---|---|---|---|---|\n`;
data.A_CONFIRMED_SEED.forEach(u => {
  md += `| ${u.email} | ${u.username} | ${u.userId} | ${u.posts} | ${u.stories} | ${u.messages} | ${u.interactionsCount} |\n`;
});
md += `\n**Total Seed Accounts:** ${data.A_CONFIRMED_SEED.length}\n\n`;

md += `## B. CONFIRMED E2E ACCOUNTS (Safe to Delete)\n`;
md += `These accounts match the known dynamic Playwright patterns (e.g. \`e2e_*@example.com\`, \`test-*@example.com\`).\n\n`;
md += `<details><summary>Click to view ${data.B_CONFIRMED_E2E.length} E2E accounts</summary>\n\n`;
md += `| Email | Username | ID | Posts | Stories | Messages | Total Interactions |\n`;
md += `|---|---|---|---|---|---|---|\n`;
data.B_CONFIRMED_E2E.forEach(u => {
  md += `| ${u.email} | ${u.username} | ${u.userId} | ${u.posts} | ${u.stories} | ${u.messages} | ${u.interactionsCount} |\n`;
});
md += `\n</details>\n\n`;

md += `## C. UNKNOWN / POSSIBLY REAL (DO NOT DELETE)\n`;
md += `These accounts end with \`@sociall.com\` or \`@example.com\` or contain "test"/"e2e" but DO NOT perfectly match the known test patterns.\n\n`;
if (data.C_UNKNOWN_POSSIBLY_REAL.length === 0) {
  md += `*No accounts fell into this category.* All accounts flagged were successfully classified as A or B.\n\n`;
} else {
  md += `| Email | Username | ID | Posts | Stories | Messages | Total Interactions |\n`;
  md += `|---|---|---|---|---|---|---|\n`;
  data.C_UNKNOWN_POSSIBLY_REAL.forEach(u => {
    md += `| ${u.email} | ${u.username} | ${u.userId} | ${u.posts} | ${u.stories} | ${u.messages} | ${u.interactionsCount} |\n`;
  });
  md += `\n**Total Unknown Accounts:** ${data.C_UNKNOWN_POSSIBLY_REAL.length}\n\n`;
}

md += `## Next Steps\n`;
md += `If you approve this classification, I will proceed to **delete all accounts in category A and B only**. No accounts in category C (if any exist) or outside of this list will be touched.\n`;

fs.writeFileSync('C:/Users/HP/.gemini/antigravity-ide/brain/d6554750-d751-45d1-b57c-832a2cd7c4ae/implementation_plan.md', md);
