export enum LogAction {
  // Authentication
  AUTH_LOGIN = 'AUTH_LOGIN',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_REGISTER = 'AUTH_REGISTER',
  AUTH_REFRESH = 'AUTH_REFRESH',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',
  GOOGLE_LOGIN = 'GOOGLE_LOGIN',
  OTP_SENT = 'OTP_SENT',
  OTP_VERIFIED = 'OTP_VERIFIED',

  // Drafts
  DRAFT_CREATE = 'DRAFT_CREATE',
  DRAFT_UPDATE = 'DRAFT_UPDATE',
  DRAFT_DELETE = 'DRAFT_DELETE',
  DRAFT_PUBLISH = 'DRAFT_PUBLISH',
  DRAFT_SCHEDULE = 'DRAFT_SCHEDULE',
  DRAFT_CANCEL_SCHEDULE = 'DRAFT_CANCEL_SCHEDULE',
  DRAFT_LIST = 'DRAFT_LIST',

  // Posts
  POST_CREATE = 'POST_CREATE',
  POST_UPDATE = 'POST_UPDATE',
  POST_DELETE = 'POST_DELETE',

  // Messages
  MESSAGE_SEND = 'MESSAGE_SEND',
  MESSAGE_DELETE = 'MESSAGE_DELETE',

  // Queue
  QUEUE_ENQUEUE = 'QUEUE_ENQUEUE',
  QUEUE_PROCESS = 'QUEUE_PROCESS',
  QUEUE_SUCCESS = 'QUEUE_SUCCESS',
  QUEUE_RETRY = 'QUEUE_RETRY',
  QUEUE_FAIL = 'QUEUE_FAIL',

  // Requests
  REQUEST_INCOMING = 'REQUEST_INCOMING',
  REQUEST_COMPLETED = 'REQUEST_COMPLETED',
  REQUEST_ERROR = 'REQUEST_ERROR',
}

export type LogActionType = LogAction;
