export enum DraftErrorCode {
  DRAFT_NOT_FOUND = 'DRAFT_NOT_FOUND',
  DRAFT_CONFLICT = 'DRAFT_CONFLICT',
  INVALID_DRAFT_STATE = 'INVALID_DRAFT_STATE',
  FORBIDDEN = 'FORBIDDEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}
