import prisma from '../../../config/db';
import { buildDraftUpdateData } from '../utils/buildDraftUpdateData';

type Draft = any; // Replace with actual Draft type if generated by Prisma

type CreateDraftDto = any; // Import actual DTO type if needed

type UpdateDraftDto = any;

export class DraftRepository {
  /**
   * Create a new draft.
   */
  async createDraft(dto: CreateDraftDto, userId: string): Promise<Draft> {
    return (prisma.post as any).create({
      data: {
        ...dto,
        userId,
        status: 'DRAFT',
      },
    });
  }

  /**
   * Find a draft by its id.
   */
  async findDraftById(id: string): Promise<Draft | null> {
    return (prisma.post as any).findUnique({
      where: { id },
    });
  }

  /**
   * Optimistic locking update – succeeds only if version matches.
   */
  async updateDraftOptimistic(
    id: string,
    version: number,
    updateDto: UpdateDraftDto,
  ): Promise<Draft | null> {
    const data = buildDraftUpdateData(updateDto);
    // Increment version atomically if the current version matches
    const result = await (prisma.post as any).updateMany({
      where: { id, version },
      data: {
        ...data,
        version: { increment: 1 },
      },
    });
    if (result.count === 0) return null;
    return this.findDraftById(id);
  }

  /**
   * Force update – ignores version.
   */
  async updateDraftForce(id: string, updateDto: UpdateDraftDto): Promise<Draft | null> {
    const data = buildDraftUpdateData(updateDto);
    const updated = await (prisma.post as any).update({
      where: { id },
      data: {
        ...data,
        version: { increment: 1 },
      },
    });
    return updated;
  }

  /**
   * Soft‑delete a draft.
   */
  async deleteDraft(id: string): Promise<boolean> {
    await (prisma.post as any).update({
      where: { id },
      data: { deletedAt: new Date() },
    });
    return true;
  }

  /**
   * List drafts for a user with cursor‑based pagination.
   */
  async listDrafts(
    userId: string,
    cursor?: string,
    limit: number = 20,
  ): Promise<Draft[]> {
    const cursorCondition = cursor ? { id: cursor } : undefined;
    return (prisma.post as any).findMany({
      where: { 
        userId, 
        deletedAt: null,
        status: { in: ['DRAFT', 'SCHEDULED'] }
      },
      orderBy: { createdAt: 'desc' },
      take: limit,
      skip: cursor ? 1 : 0,
      cursor: cursorCondition,
    });
  }

  /**
   * Count drafts for a user.
   */
  async countDrafts(userId: string): Promise<number> {
    return (prisma.post as any).count({
      where: { 
        userId, 
        deletedAt: null,
        status: { in: ['DRAFT', 'SCHEDULED'] }
      },
    });
  }
}

export default new DraftRepository();
